# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jasantunes.github.io
title: Joao Antunes
email: jasantunes@gmail.com
author: Joao Antunes
description: "I am a software engineer at Entelo, a startup company located in San Francisco, CA. Before coming to the US I worked as a researcher at LaSIGE (a research lab in the the University of Lisboa (UL), Portugal, while doing my PhD in network attack injection."
copyright: 'Copyright &copy; 2017 Joao Antunes. All Rights Reserved.'
credits: 'Credits: Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/jasantunes
  - title: linkedin
    url: https://www.linkedin.com/in/jantunes

