# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://jasantunes.github.io
title: Joao Antunes
author: Joao Antunes
email: jasantunes@gmail.com
description: "I am an Engineering Leader with almost 10 years of experience in professional software development and 3+ YoE of managing teams of software engineers, I also have a strong background in backend and distributed systems, including a PhD in Network Security with 7+ YoE in pan-european research projects, and I am the author of several international research papers, patents in network performance monitoring and search relevance, and two books on network attack injection."
copyright: 'Copyright &copy; 2021 Joao Antunes. All Rights Reserved.'
credits: 'Theme: <a href="https://github.com/swcool/landing-page-theme">landing-page-theme</a>.'
lang: en-US

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
social:
  - title: GitHub
    icon: fa-github
    url: https://github.com/jasantunes
  - title: LinkedIn
    icon: fa-linkedin
    url: https://www.linkedin.com/in/jantunes
  - title: CV
    icon: fa-file-pdf-o
    url: https://bit.ly/joao-cv
    # original Google Docs document: https://docs.google.com/presentation/d/1jCtgYrRNXdDD81FhaCY-mzKVQwYi1Bmb1PEp-YB8YLc

google_analytics: UA-17910784-4
